#ifndef TIPOERROR_H_INCLUDED
#define TIPOERROR_H_INCLUDED
typedef enum {SIN_ERROR, LIBRO_YA_EXISTE, AUTOR_YA_EXISTE, AUTOR_NO_REGISTRADO, FECHA_NO_VALIDA, ANIO_ESCOLAR_NO_VALIDO} TipoError;


#endif // TIPOERROR_H_INCLUDED
